gajus/slonik

src/factories/index.js
src/index.js

This is part of the documentation:
```js
import {
createTypeParserPreset
} from 'slonik';
createPool('postgres://', {
typeParsers: [
...createTypeParserPreset()
]
});
```
But `createTypeParserPreset` is not part of the root `index.js`. This PR adds it to the exports.

fix: export createTypeParserPreset from root index

---

.README/ERROR_HANDLING.md

I've been hitting some pain points with knex recently, and slonik looks like it will suit my project.
I noticed the integrity constraint error codes were all the same, so here is an updated ERROR_HANDLING.md.

Docs: Correct PostgreSQL error names

---

src/factories/createClientConfiguration.js
test/slonik/factories/createClientConfiguration.js

Fixes #57.
Checks for a specific instance of the empty array in the default config, so that we can appease type-checking (sort of) but still know whether the user passed their own empty array of type parsers.
Still had some odd fight with the typechecker. I've used TypeScript a good bit but never Flow, so I'm not sure if I handled that in the best way.

fix: allow disabling default typeParsers

---

.README/QUERY_BUILDING.md
README.md

This section ("Difference from JSON.stringify") is repeated, probably from a copy-paste.

remove extra section in the Query Building section

---

src/sqlFragmentFactories/createJsonSqlFragment.js
test/slonik/templateTags/sql/json.js

I was working on something that took a passed unknown value (typed as `SerializableValueType`) and would write/read it from the database. I noticed that things worked fine for complex javascript objects/arrrays like `[{foo: 'bar'}]` but not when I passed in a string. This problem only occurred when I was using `sql.json` to encode the value. If I manually called `JSON.stringify` on the value, then it would be inserted into the database successfully.
I investigated and am providing this patch

Allow sql.json to encode primitive values

---

src/QueryStream.js
src/connectionMethods/stream.js

This is the more elegant fix for https://github.com/gajus/slonik/issues/189
I have reversed changes from https://github.com/gajus/slonik/pull/190 and added this fix:
https://github.com/brianc/node-postgres/pull/2271/files

fix: expose cursor result property on query stream

---

src/factories/createPoolConfiguration.js

A connection string may contain ssl related query parameters. For
example: 'sslcert=/path/tocert'. This will add the contents of the
certificate to { ssl: { cert: '...' } }.
We continue to default rejectUnauthorized if ssl is turned on, but now
we respect all ssl configuration settings specified in the connection
string.

Preserve ssl configuration in connection string

---

package.json

@gajus just tried v23 in a typescript project which happened not to have roarr types pre-installed. There's a build error because slonik re-exports a type from roarr's domain: 
https://github.com/gajus/slonik/blob/8f00e592186d3b751a04a4ed4c5fc2f7fbc47ecc/src/types.ts#L12-L14
https://github.com/gajus/slonik/blob/8f00e592186d3b751a04a4ed4c5fc2f7fbc47ecc/src/types.ts#L20-L22
That's fine, but it means that the roarr types are now a full dependency, not just dev, because downstream consumers now care about them. A peer dependency would also work but it's unnecessary inconvenient, and the types are very light, since they contain no runtime code.

fix: promote @types/roarr to a prod dependency

---

src/types.ts

In Type definition from DefinitelyTyped/@types/slonik TypeNameIdentifierType included 'uuid' as an accepted type.
This was needed for writing queries like `sql.array([...], 'uuid')`
Re-added 'uuid' to TypeNameIdentifierType.
re #195, re DefinitelyTyped/DefinitelyTyped#42632, fix #135

fix(types): re-add 'uuid' as part of TypeNameIdentifierType

---

.eslintrc
src/types.ts
test/slonik/templateTags/sql/json.ts

Some notes:
1. I was getting lots of "Invalid group length in numeric value  unicorn/numeric-separators-style" eslint errors, which I thought was perhaps a recent addition to a base eslint dep? In any case I excluded this in the .eslintrc file.
2. The added test case will succeed even if SerializableValueType isn't modified BUT running `npm run type-check` would correctly fail so I think that is sufficient.

fix: allow SerializableValueType to include Record types with optional fields (fixes #222)

---

src/index.ts
src/types.ts
test/dts.ts

This was exported in the separate type declarations, and it's a useful helper.
Fixes #217

fix(types): export CommonQueryMethodsType

---

src/index.ts

Discovered after upgrading and a call to `sql.array()` was no longer possible without tricking the compiler with `... as unknown as SqlTokenType`

fix(types): export TypeNameIdentifierType

---

src/errors.ts
test/slonik/errors.ts
test/slonik/integration.ts

feat: include pg message in errors

---

src/binders/bindPool.ts
src/types.ts
test/dts.ts
test/slonik/factories/createPool.ts

Fixes #242 
@gajus you'd mentioned that we should only surface what's needed, and I did try that out, but I couldn't find a way that seemed right. Exposing only part of the resolved configuration feels dangerous to me, because it'd be easy to try to create a new pool with an old one's settings, and assume that important fields like `interceptors`, `idleTimeout` etc. were copied over.
Another way to think of it: it's only exposing _one_ field, `configuration`. Any breaking changes on `ClientConfigurationType` are already breaking since it's used as the input to `createPool`.

feat: expose pool configuration

---

src/binders/bindTransactionConnection.ts
src/types.ts
test/slonik/integration.ts

as discussed in #252. happy to make any other changes of course. and also happy to not include the test if it's frivolous.

feat: allow .stream() on transaction binders (#252)

---

src/factories/createSqlTag.ts
src/sqlFragmentFactories/createBinarySqlFragment.ts
src/types.ts
test/slonik/integration.ts

The multi-column variants (`any`, `many`, `maybeOne`, `one`, `query`) always return a hash.
The single-column variants (`anyFirst`, `manyFirst`, `maybeOneFirst`, `oneFirst`) always return a single column type.
This PR makes it harder to use the wrong one.
```ts
// correct
connection.any<{ col1: number, col2: string}>(sql`...`)
connection.anyFirst<number>(sql`...`)
// incorrect
connection.any<string>(sql`...`)
connection.anyFirst<{ foo: number }>(sql`...`)
```
This change caught one such bug in the test suite.

Improve type safety for query methods

---

src/types.ts
test/types.ts

The first commit 5b17a71 reproduces the problem and the second commit 5e37def fixes it. **I would recommend a squash-and-merge commit to avoid having the intermediate "red" commit in master**.
Since no existing type-level tests regressed, we can be pretty confident that this won't break any further use cases (e.g. we can see that the type restrictions actually _weren't_ helping make the overall type-safety any better, since we have plenty of tests that ensure the various query methods return appropriate types). If anyone can think of more type-level test cases to add, please feel free to comment.
Closes #267 
Closes #276
Related: #268
Related: #270
Related: https://github.com/gajus/slonik/commit/09c7db1611214dfa44d385b84dc7b034e745124b
Related #265 (the PR that caused all the chaos!)
As a …

Fix types for rows with jsonb fields

---

.README/TYPES.md
README.md
src/types.ts
test/types.ts

I missed a couple of cases when removing generic constraints from helper methods. Helpfully renovate found them quickly: https://github.com/mmkal/slonik-tools/pull/275

fix: allow interface in `sql` typearg

---

src/connectionMethods/copyFromBinary.ts
src/utilities/encodeTupleList.ts

This fixes #293. I've updated the `node-pg-copy-streams-binary` API call which fixed the described error. But then the `copyFromBinary` promise still wouldn't resolve. Turns out it was listening to the stream's `end` event instead of `finish`. It now resolves as expected.

fixed copyFromBinary

---

src/factories/createPool.ts

Turns out you can turn `typeof Pg | null` from @types/pg into `typeof Pg` using Exclude type

style: Replace non-null type assertion

---

.README/QUERY_BUILDING.md
.README/RECIPES.md
README.md
src/factories/createSqlTag.ts
src/types.ts
src/utilities/escapeIdentifier.ts
src/utilities/escapeLiteralValue.ts
src/utilities/index.ts
test/slonik/templateTags/sql/literalValue.ts
test/slonik/utilities/escapeIdentifier.ts
test/slonik/utilities/escapeLiteralValue.ts

Adds an unsafe method for interpolating literal values into queries.
This method is added exclusively for building utility statements (e.g. CREATE USER).

feat: add literalValue (fixes #309, #150)

---

.README/QUERY_METHODS.md
.README/README.md
.README/USAGE.md
README.md
src/binders/bindPool.ts
src/binders/bindPoolConnection.ts
src/binders/bindTransactionConnection.ts
src/connectionMethods/nestedTransaction.ts
src/connectionMethods/transaction.ts
src/constants.ts
src/factories/createClientConfiguration.ts
src/routines/executeQuery.ts
src/types.ts
test/helpers/createClientConfiguration.ts
test/helpers/createErrorWithCode.ts
test/helpers/createIntegrationTests.ts
test/slonik/connectionMethods/nestedTransaction.ts
test/slonik/connectionMethods/query/query.ts
test/slonik/connectionMethods/transaction.ts
test/slonik/factories/createClientConfiguration.ts
test/slonik/routines/executeQuery.ts

Move transaction retry handling to the transaction and nestedTransaction
methods and change it so that the handler function is called again
instead of just replaying the queries that are part of the transaction.
Fixes #163.
Add a second parameter to the transaction method to allow users to
define a retry limit per transaction. If a retry limit is given for a
transaction then the global defined retry limit for transactions is
ignored.
Change executeQuery so that it retries individual queries that failed
with a transaction rollback error. Only queries that are not part of a
transaction are retried. The number of times a query is retried is
specified by the global queryRetryLimit configuration. Fixes #176.
The above change also fixes #196 since the transactionQueries array no
longer exists.

Change query retry handling

---

src/utilities/parseDsn.ts
src/utilities/stringifyDsn.ts
test/slonik/utilities/parseDsn.ts
test/slonik/utilities/stringifyDsn.ts

DB-connection parameters might have url-incompatible characters in them (such as `/`). The standard way of dealing with this is urlencoding.
Slonik's old DSN parser supported it, but new one doesn't.
This patch adds urldecoding and urlencoding for username, password and databaseName.

Make sure that parts of DSN are properly decoded

---

src/declarations.d.ts
src/routines/executeQuery.ts
src/types.ts

An idea: it's frustrating that when there are errors in a query, the call-stacks are always full of `pg-protocol` and related sites, never much to do with the application code. `captureStackTrace` can help. Here's roughly what I want to do:
```ts
const pool = createPool('postgresql://postgres:postgres@localhost:5433/postgres', {
captureStackTrace: true,
interceptors: [
{
queryExecutionError: (context, query, error, notices) => {
console.log({context, query, error, notices})
if (context.stackTrace) {
throw Object.assign(new Error(error.message), {
stack:
`${error.message}\n` +
context.stackTrace
.map(site => {
const location = `${site.fileName}:${site.lineNumber}:${site.columnNumber}`
return `    at ${site.functionName || '[unknown]'} (${location})`
})
.join('\n'),
cause: error,
})
}
},
}, …
```

Add functionName to callsite frames

---

src/QueryStream.ts
src/binders/bindPool.ts
src/binders/bindPoolConnection.ts
src/connectionMethods/stream.ts
src/types.ts
test/slonik/integration/pg.ts

The `pool.stream` method is prohibitively slow when working with large amounts of data because the QueryStream is configured to fetch 100 rows at a time. Being able to control the number of rows fetched would allow us to find the right balance between execution speed and memory consumption.
This PR adds a config parameter to the `pool.stream` method which allows us to specify the batchSize used in the QueryStream.

Added config parameter to stream with batch size

---

.README/UTILITIES.md
README.md

Removed `connect_timeout` parameter in `parseDsn` and replaced with a correct example in `stringifyDsn`.

Docs: replace with appropriate examples in the utilities section

---

package.json
src/factories/createConnection.ts
test/slonik/binders/bindPool/connect.ts

I cannot recall the reason for the earlier implementation, but it was either because pg-pool did not provide a method to destroy connection upon release or because I was not familiar with that functionality.

feat: simplify logic behind destroying connection clients

---

src/binders/bindPoolConnection.ts
src/binders/bindTransactionConnection.ts
src/connectionMethods/any.ts
src/connectionMethods/anyFirst.ts
src/connectionMethods/copyFromBinary.ts
src/connectionMethods/exists.ts
src/connectionMethods/many.ts
src/connectionMethods/manyFirst.ts
src/connectionMethods/maybeOne.ts
src/connectionMethods/maybeOneFirst.ts
src/connectionMethods/one.ts
src/connectionMethods/oneFirst.ts
src/connectionMethods/query.ts
src/connectionMethods/stream.ts
src/routines/executeQuery.ts
src/types.ts
test/slonik/routines/executeQuery.ts

This makes it easier to introduce additional properties associated with the query, such as the zod object.

refactor: pass the entire tagged template

---

.README/README.md

This is a simple readme-only update that points users to the [vscode-sql-lit](https://marketplace.visualstudio.com/items?itemName=thebearingedge.vscode-sql-lit) extension.
The extension was recently updated and supports SQL highlighting even when using the ``sql.type(zodType)`SELECT * from Users`;`` syntax, unlike the previously recommended extension.

Update VS code SQL highlighting extension

---

.README/RUNTIME_VALIDATION.md
README.md
src/assertions.ts
src/errors.ts
src/factories/createSqlTag.ts
src/index.ts
src/routines/executeQuery.ts
src/types.ts
test/slonik/connectionMethods/one.ts
test/slonik/templateTags/sql/sql.ts
test/types.ts

BREAKING CHANGE:
* drops `ParserIssue` and `Parser<T>`, which were Zod-like types in favor of using Zod
* drops `.strict()`
* drops the ability to hint return type using an arbitrary object (use `sql.type` instead)
* drops the ability to hint return type using interfaces (use `sql.type` instead)
* exports `SchemaValidationError`
* fixes #398 
* fixes #397 
Context around the changes:
As we rolled out `sql.type` across our repositories in contra.com, it became clear that every use of `sql<T>` is an anti-pattern. Furthermore, the earlier implementation meant that we could not fully leverage the power of [Zod](https://github.com/colinhacks/zod) to extend and manipulate result types/shape (see #398 and #397). As such, this release is a stepping stone towards abandoning `sql<T>` in favor of …

Adopt MixedRow

---

src/utilities/parseDsn.ts
test/slonik/utilities/parseDsn.ts

This PR allows the [connection string host to be url encoded](https://stackoverflow.com/questions/27037990/connecting-to-postgres-via-database-url-and-unix-socket-in-rails), which is needed for Google Cloud run to connect to the UNIX socket.
When connecting to Google Cloud SQL from Google Cloud Run, the default and recommended way to is to use a provided UNIX socket located at `/cloudsql/<project-id>:<region-name>:<sql-instance>`. However, to connect to that socket, the host must be provided as a URL-encoded string like `%2Fcloudsql%2F<project-id>%3A<region-name>%3Ar<sql-instance>`. Before [`slonik@25.1.0`](https://github.com/gajus/slonik/compare/v25.0.0...v25.1.0#diff-2b0be5180a88e7bd8b976003ef86aaa905781e76c629013b0b4235c0d15e6b6eR15), this worked properly because the connection URI was …

Allow URL encoded host in parseDSN

---

src/QueryStream.ts
src/connectionMethods/stream.ts
test/slonik/integration/pg.ts

Close underlying QueryStream on stream.destroy()

---

src/factories/createSqlTag.ts

This is my attempt at fixing typing for `createSqlTag()`. See #432 for the bug I'm attempting to fix with this.
The current definition leaves the type of the key of the `typeAliases` object too wide by default, making it unknown and thus unusable as a Record key. This leads to a TypeScript compilation error. This pull request makes the key type extend `PropertyKey` instead making only valid Record key types assignable as the key type.

Fix createSqlTag typing

---

.README/RUNTIME_VALIDATION.md
README.md

The current docs state that slonik will throw for unknown keys.
However, Zod does not throw for unknown keys by default, you'd have to tell it to.
The current docs are likely a relict of previous behaviour.

Fix docs about unknown keys

---

.README/INTERCEPTORS.md
.README/RUNTIME_VALIDATION.md
README.md
src/connectionMethods/stream.ts
src/routines/executeQuery.ts
src/types.ts
test/slonik/connectionMethods/query/interceptors/transformRow.ts
test/slonik/integration/stream.ts

This implements the changes outlined in #539.
I also took the liberty of pulling up the "Result parser interceptor" section to the beginning of the runtime_validation section.
This felt reasonable, since this is the initial setup without which none of the following info would work.
I realise this makes reviewing the changes a bit more difficult, so here they are:
- [line 24](https://github.com/gajus/slonik/pull/540/files#diff-0f9cfa6ab7e48e7434ebbb29e5561db27af0193ce3830c703eb05360b6e826beR24): added "based on" as it's not exactly the original implementation anymore.
- [line 39](https://github.com/gajus/slonik/pull/540/files#diff-0f9cfa6ab7e48e7434ebbb29e5561db27af0193ce3830c703eb05360b6e826beR39): added 'async'
- [line 46](https://github.com/gajus/slonik/pull/540/files#diff-0f9cfa6ab7e48e …

Make row transforms async

---

.github/workflows/feature.yaml
.github/workflows/main.yaml

Fixes:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chore: update github actions to use node 20

---

README.md

The current link for "The History of Slonik, the PostgreSQL Elephant Logo" in the README leads to a 404 page on Vertabelo's website, and I wasn't able to find the article in their blog. This switches it to a working link on LearnSQL which I think probably has the same content since it has the same title

Update history of slonik link in readme

---

packages/sql-tag/src/factories/createSqlTag.test/sql.test.ts
packages/sql-tag/src/factories/createSqlTag.ts

* in typescript: protects using types
* in javascript: protects by checking for strings.raw
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#raw_strings
Closes #589

Protect against unsafe sql.fragment usage

---

.changeset/giant-chicken-help.md
packages/slonik/src/factories/createConnectionPool.ts
packages/slonik/src/helpers.test/createIntegrationTests.ts

There is an issue with `pool.end()`. If you have multiple idle connections and then call `pool.end()` it will actually only close a subset of the idle connections. The reason is that as part of `onDestory` there is a splice operation on the global `connections` array. As `pool.end()` is mapping over `connections` we're removing items from the array so it misses some.
So what actually happens today:
1. Open 5 connections
1. Call `await pool.end()`
2. Only 3 of the connections are closed, `pool.end()` resolves
3. Once `idleTimeout` expires for the remaining 2 connections, those 2 will be closed as well
- This is where it gets problematic. If you have a high `idleTimeout` setting, there will be hanging connections until `idleTimeout` is hit, even after `pool.end()` resolves
Simple …

fix: close all connections in pool.end()
