README.md

anyFirst() example calls any()

Fix minor README error

---

.README/SQL_TAG.md
.README/TYPE_PARSERS.md
.README/USAGE.md
README.md

Sometiems -> Sometimes && Implemnatation -> Implementation

Fix a couples of typos in the documentation

---

.README/QUERY_BUILDING.md
README.md

keywrods -> keywords; propery -> property;

---

.README/TESTING.md
src/routines/executeQuery.js
src/types.js
test/slonik/integration.js

This pull request is for add details to error.
All notices generate during transaction is now add to Error object.
Related to #110

feat: add notices on error

---

.README/QUERY_METHODS.md
README.md

Fix for a typo in readme

---

.README/ABOUT_SLONIK.md

Changes Flow opaque type to TypeScript type alias.

docs: remove opaque type

---

src/index.ts

Export the SerializableValueType type

---

src/factories/createConnection.ts
test/slonik/binders/bindPool/connect.ts

fixes https://github.com/gajus/slonik/issues/256

dont close connection after `IMPLICIT_TRANSACTION` query

---

test/dts.ts
test/slonik/integration.ts

https://travis-ci.com/github/gajus/slonik/builds/220691808

Fix failing build due to lint error

---

.README/INTERCEPTORS.md
README.md

Small documentation update to include some information about beforePoolConnection

docs: Document beforePoolConnection

---

.README/QUERY_BUILDING.md
README.md
src/factories/createSqlTag.ts
src/sqlFragmentFactories/createUnnestSqlFragment.ts
src/types.ts
test/slonik/templateTags/sql/unnest.ts

feat: sql.identifier-like column types for sql.unnest

---

src/factories/createPrimitiveValueExpressions.ts
test/slonik/templateTags/sql/join.ts

Add Buffer support to primitive value expressions

---

.README/README.md
.README/RUNTIME_VALIDATION.md
README.md
package-lock.json
package.json
src/errors.ts
src/factories/createSqlTag.ts
src/routines/executeQuery.ts
src/types.ts
test/slonik/connectionMethods/one.ts
test/slonik/connectionMethods/oneFirst.ts
test/slonik/templateTags/sql/sql.ts
test/types.ts

Backward compatible addition of runtime validation.
Shoutout to @mmkal for helping with backward compatibility and other design decisions.
Supersedes:
* https://github.com/gajus/slonik/pull/371
* https://github.com/gajus/slonik/pull/369

feat: add runtime result validation using zod

---

src/utilities/safeStringify.ts

Use strict stringify

---

src/factories/createPool.ts

This PR proposes a solution to #475. Thank you very much and please let me know what I can do to help here!

fix: always call `.end()` on PgClient setup instance

---

src/factories/createSqlTag.ts
test/slonik/templateTags/sql/sql.ts

Include index in error when trying to bind undefined value

---

src/factories/createMockQueryResult.ts

Take all keys from first row, unspecified datatype (0). (fixes #232)

feat: Add field names in mockQueryResult

---

src/factories/createPrimitiveValueExpressions.ts
test/slonik/templateTags/sql/join.ts

Fix bigint in sql.join

---

.README/README.md
README.md
src/index.ts
src/types.ts

should be pretty straight forward. :)
At some point you might want to add in more docs for better mocking/testing.
Maybe using `createPoolWithSpy`?

clean up slonik mocking remnants

---

packages/errors/src/errors.ts
packages/errors/tsconfig.json

fix(errors): update tslib to 2022

---

README.md

Small PR - Commit d69a83d379dfa5ac68226717dfcbe617bbd041f1 moved `types.ts`. This PR adjusts sources to changes.

fix: update `types.ts` reference
